test:
	go test -v ./...

test-bench:
	go test -v -bench=. ./...

test-besch-mem:
	go test -v -bench=. -benchmem -memprofile=mem.out ./...

test-bench-cpu:
	go test -v -bench=. -cpuprofile=cpu.out ./...
